name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install packages
        run: |
          poetry run make config-poetry
          poetry run make install-all

      - name: Show installed packages
        run: |
          poetry run poetry show
          poetry run poetry show --tree

      - name: check grizz
        run: |
          poetry run python -c "import grizz"
      - name: check grizz.ingestor
        run: |
          poetry run python -c "from grizz import ingestor"
      - name: check grizz.testing
        run: |
          poetry run python -c "from grizz import testing"
      - name: check grizz.transformer
        run: |
          poetry run python -c "from grizz import transformer"
      - name: check grizz.utils
        run: |
          poetry run python -c "from grizz import utils"
