name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read


jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set environment variable
        run: |
          echo $(poetry run poetry env info --path)/bin >> $GITHUB_PATH

      - name: Install packages
        run: |
          make install-all

      - name: Show installed packages
        run: |
          poetry show
          poetry show --tree

      - name: check grizz
        run: |
          python -c "import grizz"
      - name: check grizz.exporter
        run: |
          python -c "from grizz import exporter"
      - name: check grizz.ingestor
        run: |
          python -c "from grizz import ingestor"
      - name: check grizz.testing
        run: |
          python -c "from grizz import testing"
      - name: check grizz.transformer
        run: |
          python -c "from grizz import transformer"
      - name: check grizz.utils
        run: |
          python -c "from grizz import utils"
